<aside class="web-trends-september-2016-artwork__background-animation">
  <h3>Background animation</h3>

  <div class="arrow move-element">
    {% set direction = "top" %}
    {% include '../../../framework/design/decorations/arrow-with-triangle/arrow-with-triangle.html.swig' %}
  </div>

  <div class="char move-element">
    <span>&bull;</span>
  </div>

  <div class="trapezoid move-element">
  </div>
</aside>
